apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-server-manager
  namespace: mcp
  labels:
    app: mcp-server-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-server-manager
  template:
    metadata:
      labels:
        app: mcp-server-manager
    spec:
      serviceAccountName: mcp-server-manager
      containers:
        - name: mcp-server-manager
          image: xnet.registry.io:8443/xnet-cloud/mcp-server-manager:4.0.3
          imagePullPolicy: Always
          ports:
            # 端口需要与 ConfigMap 中的 port 配置一致
            - name: es-mcp
              containerPort: 8088
            - name: test-mcp
              containerPort: 8091
            - name: helm-mcp
              containerPort: 8092
          volumeMounts:
            - name: config
              mountPath: /app/config
              readOnly: true
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
      volumes:
        - name: config
          configMap:
            name: mcp-config
